outpath:
    analysis

gurobi:
    license: gurobi.lic
    timeout: 1


exec:
    match_trie    : py/match_lr_bc-trie.py
    match_aln     : py/match_lr_bc-aln.py
    extract_lr_bc : py/extract_lr_bc.py
    select_sr_bc  : py/extract_top_sr_br.py

gene_cell_seed_sr_lr:
    - '100-50-42-1000000-100000'
    - '3000-500-42-15000000-1000000'
    - '20000-5000-42-150000000-5000000'

# sim_samples:
#     - N

samples:
    sim_S:
        ref: homo_sapiens
        reads:
            - data/simulation/long-reads/S_lr.fq
        truth:
            data/simulation/truth/S.truth.tsv.gz
        sr_fastq_dir:
            data/simulation/short-reads/S
        sr_fastq_prefix:
            hg_100
        sr_reads:
            R1: data/simulation/short-reads/S/hg_100_S1_L001_R1_001.fastq.gz
            R2: data/simulation/short-reads/S/hg_100_S1_L001_R2_001.fastq.gz
    sim_M:
        ref: homo_sapiens
        reads:
            - data/simulation/long-reads/M_lr.fq
        truth:
            data/simulation/truth/M.truth.tsv.gz
        sr_fastq_dir:
            data/simulation/short-reads/M
        sr_fastq_prefix:
            hg_100
        sr_reads:
            R1: data/simulation/short-reads/M/hg_100_S1_L001_R1_001.fastq.gz
            R2: data/simulation/short-reads/M/hg_100_S1_L001_R2_001.fastq.gz
    sim_L:
        ref: homo_sapiens
        reads:
            - data/simulation/long-reads/L_lr.fq
        truth:
            data/simulation/truth/L.truth.tsv.gz
        sr_fastq_dir:
            data/simulation/short-reads/L
        sr_fastq_prefix:
            hg_100
        sr_reads:
            R1: data/simulation/short-reads/L/hg_100_S1_L001_R1_001.fastq.gz
            R2: data/simulation/short-reads/L/hg_100_S1_L001_R2_001.fastq.gz
    NOA1_trim:
        reads:
            - data/real_trim/long-read/NOA1_trim.fq
        top_bc:
            - data/real_trim/short-read-barcodes/NOA1_trim.sr_bc.TOP.tsv.gz
    NOA2_trim:
        reads:
            - data/real_trim/long-read/NOA2_trim.fq
        top_bc:
            - data/real_trim/short-read-barcodes/NOA2_trim.sr_bc.TOP.tsv.gz
    N_trim:
        reads:
            - data/real_trim/long-read/N_trim.fq
        top_bc:
            - data/real_trim/short-read-barcodes/N_trim.sr_bc.TOP.tsv.gz
    NOA1:
        ref: homo_sapiens
        reads:
            - /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/long-read/PAG34747_C1_pass_fastq_concat.fastq
        sr_fastq_dir:
            /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/scrna/fastq/13035_C1_GSC
        sr_fastq_prefix:
            13035_C1
        sr_reads:
            R1: /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/scrna/fastq/13035_C1_GSC/13035_C1_S1_L001_R1_001.fastq.gz
            R2: /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/scrna/fastq/13035_C1_GSC/13035_C1_S1_L001_R2_001.fastq.gz
        cell_count:
            5000
    NOA2:
        ref: homo_sapiens
        reads:
            - /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/long-read/PAG34747_D1_pass_fastq_concat.fastq
        sr_fastq_dir:
            /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/scrna/fastq/13035_D1_GSC
        sr_fastq_prefix:
            13035_D1
        sr_reads:
            R1: /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/scrna/fastq/13035_D1_GSC/13035_D1_S1_L001_R1_001.fastq.gz
            R2: /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/scrna/fastq/13035_D1_GSC/13035_D1_S1_L001_R2_001.fastq.gz
        cell_count:
            5000
    N:
        ref: homo_sapiens
        reads:
            - /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/long-read/PAG34747_N1_pass_fastq_concat.fastq
        sr_fastq_dir:
            /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/scrna/fastq/13032_N1_GSC
        sr_fastq_prefix:
            13032_N1
        sr_reads:
            R1: /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/scrna/fastq/13032_N1_GSC/13032_N1_S1_L001_R1_001.fastq.gz
            R2: /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/scrna/fastq/13032_N1_GSC/13032_N1_S1_L001_R2_001.fastq.gz
        cell_count:
            5000

references:
    homo_sapiens:
        annot          : data/annotations/GTF/97/Homo_sapiens.GRCh38.97.gtf
        transcriptome  : data/annotations/cDNA/97/Homo_sapiens.GRCh38.cdna.all.fa
        genome         : data/annotations/DNA/97/Homo_sapiens.GRCh38.dna.primary_assembly.fa
        genome_fai     : data/annotations/DNA/97/Homo_sapiens.GRCh38.dna.primary_assembly.fa.fai
        cellranger_ref : data/annotations/CellRanger/refdata-cellranger-GRCh38-1.2.0

salmon_refs:
    annot          : data/annotations/GTF/GENCODE/38/human.gencode.v38.annotation.gtf
    transcriptome  : data/annotations/cDNA/GENCODE/38/human.gencode.v38.pc_transcripts.fa
    genome         : data/annotations/DNA/GENCODE/38/human.GRCh38.primary_assembly.genome.fa
    whitelist      : data/annotations/3M-february-2018.txt
