outpath:
    analysis

gurobi:
    license: gurobi.lic
    timeout: 1


exec:
    match_trie    : py/match_lr_bc-trie.py
    match_aln     : py/match_lr_bc-aln.py
    extract_lr_bc : py/extract_lr_bc.py
    select_sr_bc  : py/extract_top_sr_br.py

gene_cell_seed_sr_lr:
    - '100-50-42-1000000-100000'
    - '3000-500-42-15000000-1000000'
    - '20000-5000-42-150000000-5000000'

sim_samples:
    - N1

samples:
    NOA1:
        ref: homo_sapiens
        reads:
            - /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/long-read/PAG34747_C1_pass_fastq_concat.fastq
        sr_fastq_dir:
            /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/scrna/fastq/13035_C1_GSC
        sr_fastq_prefix:
            13035_C1
        sr_reads:
            R1: /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/scrna/fastq/13035_C1_GSC/13035_C1_S1_L001_R1_001.fastq.gz
            R2: /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/scrna/fastq/13035_C1_GSC/13035_C1_S1_L001_R2_001.fastq.gz
        cell_count:
            5000
    NOA2:
        ref: homo_sapiens
        reads:
            - /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/long-read/PAG34747_D1_pass_fastq_concat.fastq
        sr_fastq_dir:
            /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/scrna/fastq/13035_D1_GSC
        sr_fastq_prefix:
            13035_D1
        sr_reads:
            R1: /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/scrna/fastq/13035_D1_GSC/13035_D1_S1_L001_R1_001.fastq.gz
            R2: /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/scrna/fastq/13035_D1_GSC/13035_D1_S1_L001_R2_001.fastq.gz
        cell_count:
            5000
    N:
        ref: homo_sapiens
        reads:
            - /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/long-read/PAG34747_N1_pass_fastq_concat.fastq
        sr_fastq_dir:
            /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/scrna/fastq/13032_N1_GSC
        sr_fastq_prefix:
            13032_N1
        sr_reads:
            R1: /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/scrna/fastq/13032_N1_GSC/13032_N1_S1_L001_R1_001.fastq.gz
            R2: /groups/hachgrp/projects/tmp-ghazal-single-cell/raw-data/scrna/fastq/13032_N1_GSC/13032_N1_S1_L001_R2_001.fastq.gz
        cell_count:
            5000

references:
    homo_sapiens:
        annot          : /groups/hachgrp/annotations/GTF/97/Homo_sapiens.GRCh38.97.gtf
        transcriptome  : /groups/hachgrp/annotations/cDNA/97/Homo_sapiens.GRCh38.cdna.all.fa
        genome         : /groups/hachgrp/annotations/DNA/97/Homo_sapiens.GRCh38.dna.primary_assembly.fa
        genome_fai     : /groups/hachgrp/annotations/DNA/97/Homo_sapiens.GRCh38.dna.primary_assembly.fa.fai
        cellranger_ref : /groups/hachgrp/annotations/CellRanger/refdata-cellranger-GRCh38-1.2.0

salmon_refs:
    annot          : /groups/hachgrp/annotations/GTF/GENCODE/38/human.gencode.v38.annotation.gtf
    transcriptome  : /groups/hachgrp/annotations/cDNA/GENCODE/38/human.gencode.v38.pc_transcripts.fa
    genome         : /groups/hachgrp/annotations/DNA/GENCODE/38/human.GRCh38.primary_assembly.genome.fa
    whitelist      : extern/3M-february-2018.txt
