doVlnPlot: TRUE
percentMt: 25
nFeatuerRNAMax: 20000
nFeatuerRNAMin: 500
preDoSave: TRUE
project: "Testis"
nCellMin: 0
vlnPltName: "features.jpg"
preDataName: "data.rds"
doEblowPlot: TRUE
maxDim: 30
doUMAP: TRUE
doSave: TRUE
nfeatures: 6000
elbowPlotName: "elbow.jpg"
UMAPName: "clustering.jpg"
dataName: "data-cluster.rds"
doDoublet: TRUE